---
layout: post
title:  "Как поймать все исключения в Fastapi"
date:   2025-04-22
categories: ru
tags: "python fastapi"
---

## Дисклеймер
Информация ниже приведена для Fastapi v0.115.5

## Проблематика
Допустим мы хотим поймать все исключения, которые могут быть выброшены в обработчиках запросов в Fastapi. Это может 
быть необходимо когда нам надо
1. Залогировать все исключения
2. Гарантировать единый формат ответов для любых ошибок

Представим, что у нас есть функция вида
```python
def error_to_response(error: Exception) -> ErrorResponse:
    """
    This function logs error and convert error to response
    """
    pass
```
Она уже написана, и она логирует ошибку и возвращает ответ, который мы можем слать клиенту. Тогда код в обработчике
будет выглядеть так
```python
@app.get("/ping")
async def ping():
    try:
        return do_ping()
    except Exception as e:
        return error_to_response(e)
```
Таким образом, в каждом обработчике у нас будет `try - except`, который должен оборачивать весь код обработчика. 
Бойлерплейтно? Еще как! Попробуем избавиться от этого блока. Уверен, что в Fastapi есть вариант, как прикрутить
обработчик ошибок глобально.





